### ISSUE TITLE
Building demos fails

### ISSUE THREAD

**Issue by mdepp** [KCL-Planning/rosplan_demos#7] opened 2019-05-14 19:33 UTC
I'm following the directions in the README, but when I get to `catkin build` it fails with this output:

```
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target _occupancy_grid_utils_generate_messages_check_deps_OverlayClouds
[  0%] Built target _occupancy_grid_utils_generate_messages_check_deps_LocalizedCloud
[  0%] Built target _occupancy_grid_utils_generate_messages_check_deps_NavigationFunction
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target nav_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target nav_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target nav_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_eus
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target nav_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target sensor_msgs_generate_messages_nodejs
[ 10%] Built target occupancy_grid_utils_generate_messages_cpp
[ 20%] Built target occupancy_grid_utils_generate_messages_lisp
[ 34%] Built target occupancy_grid_utils_generate_messages_py
[ 48%] Built target occupancy_grid_utils_generate_messages_eus
[ 58%] Built target occupancy_grid_utils_generate_messages_nodejs
[ 58%] Built target occupancy_grid_utils_generate_messages
[ 86%] Built target grid_utils
[ 93%] Built target grid_construction_node
[ 96%] [32m[1mLinking CXX shared library /home/mdepp/ros_ws/devel/.private/occupancy_grid_utils/lib/libgrid_utils_boost_python_exports.so[0m
/usr/bin/ld: /home/mdepp/source/pyenv/versions/2.7.16/lib/libpython2.7.a(boolobject.o): relocation R_X86_64_32 against `.data' can not be used when making a shared object; recompile with -fPIC
/home/mdepp/source/pyenv/versions/2.7.16/lib/libpython2.7.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
CMakeFiles/grid_utils_boost_python_exports.dir/build.make:186: recipe for target '/home/mdepp/ros_ws/devel/.private/occupancy_grid_utils/lib/libgrid_utils_boost_python_exports.so' failed
CMakeFiles/Makefile2:1291: recipe for target 'CMakeFiles/grid_utils_boost_python_exports.dir/all' failed
Makefile:138: recipe for target 'all' failed
make[2]: *** [/home/mdepp/ros_ws/devel/.private/occupancy_grid_utils/lib/libgrid_utils_boost_python_exports.so] Error 1
make[1]: *** [CMakeFiles/grid_utils_boost_python_exports.dir/all] Error 2
make: *** [all] Error 2
```
I'm using Ubuntu 16.04 and ros kinetic.

**Comment by gerardcanal** [comment] 2019-05-14 20:03
Hi mdepp,
I believe that the problem is not related to ROSPlan or ROSPlan demos. It looks to me that the error belongs to files from the occupancy_grid_utils package, which is not created nor maintained by ROSPlan developers. 

Please try to build this package (occupancy_grid_utils) alone to make sure that it is not related to rosplan.  It looks like it may be some python versioning problem or missing python dependency.

**Comment by oscar-lima** [comment] 2019-05-14 20:49
Check this [post](https://answers.ros.org/question/282858/catkin_make-problem-opencv-python-ros-kinetic/) from ROS Answers describing a similar issue, it points to python having being compiled from source using incorrect flags, is this the case?

**Comment by oscar-lima** [comment] 2019-05-14 20:59
Try [this](https://stackoverflow.com/questions/42582712/relocation-r-x86-64-32s-against-py-notimplementedstruct-can-not-be-used-when) :

The solution was to reinstall the pyenv-provided Python with the flag set like this:

PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install --force 2.7.11

To ensure this gets used: machine: python: version: 2.7.11 # Has to match the pyenv-installed version

**Comment by mdepp** [comment] 2019-05-14 21:05
Thanks! It looks like the Python from pyenv was the issue, since that last suggestion fixed things so it now builds properly.

**Comment by oscar-lima** [comment] 2019-05-14 21:22
Great! Thanks for the feedback! Closing issue now 👌🏼

**Closed as completed by oscar-lima** 2019-05-14 21:22 UTC
